# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm3.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(959, 834)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainArea = QtWidgets.QGroupBox(self.centralwidget)
        self.MainArea.setEnabled(True)
        self.MainArea.setTitle("")
        self.MainArea.setAlignment(QtCore.Qt.AlignCenter)
        self.MainArea.setCheckable(False)
        self.MainArea.setObjectName("MainArea")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MainArea)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainarea1 = QtWidgets.QFrame(self.MainArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainarea1.sizePolicy().hasHeightForWidth())
        self.mainarea1.setSizePolicy(sizePolicy)
        self.mainarea1.setFrameShape(QtWidgets.QFrame.Box)
        self.mainarea1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mainarea1.setObjectName("mainarea1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.mainarea1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.personalButton = QtWidgets.QPushButton(self.mainarea1)
        self.personalButton.setObjectName("personalButton")
        self.horizontalLayout_5.addWidget(self.personalButton)
        self.fileButton = QtWidgets.QPushButton(self.mainarea1)
        self.fileButton.setEnabled(False)
        self.fileButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout_5.addWidget(self.fileButton)
        self.fallButton = QtWidgets.QPushButton(self.mainarea1)
        self.fallButton.setEnabled(False)
        self.fallButton.setObjectName("fallButton")
        self.horizontalLayout_5.addWidget(self.fallButton)
        self.saveButton = QtWidgets.QPushButton(self.mainarea1)
        self.saveButton.setEnabled(False)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_5.addWidget(self.saveButton)
        self.verticalLayout.addWidget(self.mainarea1)
        self.line_2 = QtWidgets.QFrame(self.MainArea)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.mainarea3 = QtWidgets.QWidget(self.MainArea)
        self.mainarea3.setObjectName("mainarea3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainarea3)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphArea = QtWidgets.QWidget(self.mainarea3)
        self.graphArea.setObjectName("graphArea")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.graphArea)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.GraphImage = QtWidgets.QLabel(self.graphArea)
        self.GraphImage.setText("")
        self.GraphImage.setObjectName("GraphImage")
        self.verticalLayout_2.addWidget(self.GraphImage)
        self.line_4 = QtWidgets.QFrame(self.graphArea)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.horizontalSlider_graph = QtWidgets.QSlider(self.graphArea)
        self.horizontalSlider_graph.setEnabled(False)
        self.horizontalSlider_graph.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_graph.setObjectName("horizontalSlider_graph")
        self.verticalLayout_2.addWidget(self.horizontalSlider_graph)
        self.menu_graph = QtWidgets.QFrame(self.graphArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_graph.sizePolicy().hasHeightForWidth())
        self.menu_graph.setSizePolicy(sizePolicy)
        self.menu_graph.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu_graph.setLineWidth(1)
        self.menu_graph.setObjectName("menu_graph")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menu_graph)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.backwardButton_graph = QtWidgets.QPushButton(self.menu_graph)
        self.backwardButton_graph.setEnabled(False)
        self.backwardButton_graph.setObjectName("backwardButton_graph")
        self.horizontalLayout_3.addWidget(self.backwardButton_graph)
        self.comboBox_graph = QtWidgets.QComboBox(self.menu_graph)
        self.comboBox_graph.setEnabled(False)
        self.comboBox_graph.setObjectName("comboBox_graph")
        self.comboBox_graph.addItem("")
        self.comboBox_graph.addItem("")
        self.comboBox_graph.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_graph)
        self.comboBox_peak = QtWidgets.QComboBox(self.menu_graph)
        self.comboBox_peak.setEnabled(False)
        self.comboBox_peak.setObjectName("comboBox_peak")
        self.comboBox_peak.addItem("")
        self.comboBox_peak.addItem("")
        self.comboBox_peak.addItem("")
        self.comboBox_peak.addItem("")
        self.comboBox_peak.addItem("")
        self.comboBox_peak.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_peak)
        self.comboBox_type = QtWidgets.QComboBox(self.menu_graph)
        self.comboBox_type.setEnabled(False)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_type)
        self.forwardButton_graph = QtWidgets.QPushButton(self.menu_graph)
        self.forwardButton_graph.setEnabled(False)
        self.forwardButton_graph.setObjectName("forwardButton_graph")
        self.horizontalLayout_3.addWidget(self.forwardButton_graph)
        self.verticalLayout_2.addWidget(self.menu_graph)
        self.horizontalLayout_2.addWidget(self.graphArea)
        self.verticalLayout.addWidget(self.mainarea3)
        self.horizontalLayout.addWidget(self.MainArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Falling Graph Analysis"))
        self.personalButton.setText(_translate("MainWindow", "Open Personal Data"))
        self.fileButton.setText(_translate("MainWindow", "Open Data File"))
        self.fallButton.setText(_translate("MainWindow", "Set Falling Point"))
        self.saveButton.setText(_translate("MainWindow", "Save File"))
        self.backwardButton_graph.setText(_translate("MainWindow", "Backward"))
        self.comboBox_graph.setItemText(0, _translate("MainWindow", "20 second"))
        self.comboBox_graph.setItemText(1, _translate("MainWindow", "1 second"))
        self.comboBox_graph.setItemText(2, _translate("MainWindow", "5 second"))
        self.comboBox_peak.setItemText(0, _translate("MainWindow", "Number of Peak"))
        self.comboBox_peak.setItemText(1, _translate("MainWindow", "Peak 1"))
        self.comboBox_peak.setItemText(2, _translate("MainWindow", "Peak 2"))
        self.comboBox_peak.setItemText(3, _translate("MainWindow", "Peak 3"))
        self.comboBox_peak.setItemText(4, _translate("MainWindow", "Peak 4"))
        self.comboBox_peak.setItemText(5, _translate("MainWindow", "Peak 5"))
        self.comboBox_type.setItemText(0, _translate("MainWindow", "Acc"))
        self.comboBox_type.setItemText(1, _translate("MainWindow", "Gyro"))
        self.forwardButton_graph.setText(_translate("MainWindow", "Forward"))


