# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm6.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(959, 834)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setEnabled(True)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainarea1 = QtWidgets.QFrame(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainarea1.sizePolicy().hasHeightForWidth())
        self.mainarea1.setSizePolicy(sizePolicy)
        self.mainarea1.setObjectName("mainarea1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.mainarea1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fileButton = QtWidgets.QPushButton(self.mainarea1)
        self.fileButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout_5.addWidget(self.fileButton)
        self.openButton = QtWidgets.QPushButton(self.mainarea1)
        self.openButton.setEnabled(True)
        self.openButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout_5.addWidget(self.openButton)
        self.slapButton = QtWidgets.QPushButton(self.mainarea1)
        self.slapButton.setEnabled(False)
        self.slapButton.setObjectName("slapButton")
        self.horizontalLayout_5.addWidget(self.slapButton)
        self.slapButton2 = QtWidgets.QPushButton(self.mainarea1)
        self.slapButton2.setEnabled(False)
        self.slapButton2.setObjectName("slapButton2")
        self.horizontalLayout_5.addWidget(self.slapButton2)
        self.fallButton = QtWidgets.QPushButton(self.mainarea1)
        self.fallButton.setEnabled(False)
        self.fallButton.setObjectName("fallButton")
        self.horizontalLayout_5.addWidget(self.fallButton)
        self.verticalLayout.addWidget(self.mainarea1)
        self.mainarea2 = QtWidgets.QFrame(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainarea2.sizePolicy().hasHeightForWidth())
        self.mainarea2.setSizePolicy(sizePolicy)
        self.mainarea2.setObjectName("mainarea2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.mainarea2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.backwardButton = QtWidgets.QPushButton(self.mainarea2)
        self.backwardButton.setEnabled(False)
        self.backwardButton.setObjectName("backwardButton")
        self.horizontalLayout_4.addWidget(self.backwardButton)
        self.startButton = QtWidgets.QPushButton(self.mainarea2)
        self.startButton.setEnabled(False)
        self.startButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.startButton.setAcceptDrops(False)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_4.addWidget(self.startButton)
        self.pauseButton = QtWidgets.QPushButton(self.mainarea2)
        self.pauseButton.setEnabled(False)
        self.pauseButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_4.addWidget(self.pauseButton)
        self.matchingButton = QtWidgets.QPushButton(self.mainarea2)
        self.matchingButton.setEnabled(False)
        self.matchingButton.setObjectName("matchingButton")
        self.horizontalLayout_4.addWidget(self.matchingButton)
        self.forwardButton = QtWidgets.QPushButton(self.mainarea2)
        self.forwardButton.setEnabled(False)
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout_4.addWidget(self.forwardButton)
        self.verticalLayout.addWidget(self.mainarea2)
        self.line = QtWidgets.QFrame(self.groupBox_5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.VideoImage = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoImage.sizePolicy().hasHeightForWidth())
        self.VideoImage.setSizePolicy(sizePolicy)
        self.VideoImage.setText("")
        self.VideoImage.setAlignment(QtCore.Qt.AlignCenter)
        self.VideoImage.setObjectName("VideoImage")
        self.verticalLayout.addWidget(self.VideoImage)
        self.video_menu = QtWidgets.QFrame(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_menu.sizePolicy().hasHeightForWidth())
        self.video_menu.setSizePolicy(sizePolicy)
        self.video_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.video_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video_menu.setObjectName("video_menu")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.video_menu)
        self.horizontalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.backwardButton_video = QtWidgets.QPushButton(self.video_menu)
        self.backwardButton_video.setEnabled(False)
        self.backwardButton_video.setObjectName("backwardButton_video")
        self.horizontalLayout_3.addWidget(self.backwardButton_video)
        self.comboBox_video = QtWidgets.QComboBox(self.video_menu)
        self.comboBox_video.setEnabled(False)
        self.comboBox_video.setObjectName("comboBox_video")
        self.comboBox_video.addItem("")
        self.comboBox_video.addItem("")
        self.comboBox_video.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_video)
        self.horizontalSlider_video = QtWidgets.QSlider(self.video_menu)
        self.horizontalSlider_video.setEnabled(False)
        self.horizontalSlider_video.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_video.setObjectName("horizontalSlider_video")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_video)
        self.forwardButton_video = QtWidgets.QPushButton(self.video_menu)
        self.forwardButton_video.setEnabled(False)
        self.forwardButton_video.setObjectName("forwardButton_video")
        self.horizontalLayout_3.addWidget(self.forwardButton_video)
        self.verticalLayout.addWidget(self.video_menu)
        self.line_2 = QtWidgets.QFrame(self.groupBox_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.GraphImage = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GraphImage.sizePolicy().hasHeightForWidth())
        self.GraphImage.setSizePolicy(sizePolicy)
        self.GraphImage.setMinimumSize(QtCore.QSize(0, 200))
        self.GraphImage.setMaximumSize(QtCore.QSize(16777215, 300))
        self.GraphImage.setText("")
        self.GraphImage.setObjectName("GraphImage")
        self.verticalLayout.addWidget(self.GraphImage)
        self.menu_graph = QtWidgets.QFrame(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_graph.sizePolicy().hasHeightForWidth())
        self.menu_graph.setSizePolicy(sizePolicy)
        self.menu_graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_graph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_graph.setObjectName("menu_graph")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.menu_graph)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backwardButton_graph = QtWidgets.QPushButton(self.menu_graph)
        self.backwardButton_graph.setEnabled(False)
        self.backwardButton_graph.setObjectName("backwardButton_graph")
        self.horizontalLayout_2.addWidget(self.backwardButton_graph)
        self.comboBox_graph = QtWidgets.QComboBox(self.menu_graph)
        self.comboBox_graph.setEnabled(False)
        self.comboBox_graph.setObjectName("comboBox_graph")
        self.comboBox_graph.addItem("")
        self.comboBox_graph.addItem("")
        self.comboBox_graph.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_graph)
        self.horizontalSlider_graph = QtWidgets.QSlider(self.menu_graph)
        self.horizontalSlider_graph.setEnabled(False)
        self.horizontalSlider_graph.setBaseSize(QtCore.QSize(10, 10))
        self.horizontalSlider_graph.setMouseTracking(True)
        self.horizontalSlider_graph.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider_graph.setStatusTip("")
        self.horizontalSlider_graph.setTracking(True)
        self.horizontalSlider_graph.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_graph.setInvertedAppearance(False)
        self.horizontalSlider_graph.setInvertedControls(False)
        self.horizontalSlider_graph.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_graph.setObjectName("horizontalSlider_graph")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_graph)
        self.comboBox_peak = QtWidgets.QComboBox(self.menu_graph)
        self.comboBox_peak.setEnabled(False)
        self.comboBox_peak.setObjectName("comboBox_peak")
        self.comboBox_peak.addItem("")
        self.comboBox_peak.addItem("")
        self.comboBox_peak.addItem("")
        self.comboBox_peak.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_peak)
        self.comboBox_type = QtWidgets.QComboBox(self.menu_graph)
        self.comboBox_type.setEnabled(False)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_type)
        self.forwardButton_graph = QtWidgets.QPushButton(self.menu_graph)
        self.forwardButton_graph.setEnabled(False)
        self.forwardButton_graph.setObjectName("forwardButton_graph")
        self.horizontalLayout_2.addWidget(self.forwardButton_graph)
        self.verticalLayout.addWidget(self.menu_graph)
        self.horizontalLayout.addWidget(self.groupBox_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Video Player with Signal"))
        self.fileButton.setText(_translate("MainWindow", "Open Data File"))
        self.openButton.setText(_translate("MainWindow", "Open Video"))
        self.slapButton.setText(_translate("MainWindow", "Save Slapping 1"))
        self.slapButton2.setText(_translate("MainWindow", "Save Slapping 2"))
        self.fallButton.setText(_translate("MainWindow", "Save Falling"))
        self.backwardButton.setText(_translate("MainWindow", "Backward"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.matchingButton.setText(_translate("MainWindow", "Matching"))
        self.forwardButton.setText(_translate("MainWindow", "Forward"))
        self.backwardButton_video.setText(_translate("MainWindow", "Backward"))
        self.comboBox_video.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_video.setItemText(1, _translate("MainWindow", "slow 1000 fps"))
        self.comboBox_video.setItemText(2, _translate("MainWindow", "iphone"))
        self.forwardButton_video.setText(_translate("MainWindow", "Forward"))
        self.backwardButton_graph.setText(_translate("MainWindow", "Backward"))
        self.comboBox_graph.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_graph.setItemText(1, _translate("MainWindow", "1 second"))
        self.comboBox_graph.setItemText(2, _translate("MainWindow", "5 second"))
        self.comboBox_peak.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_peak.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_peak.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_peak.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_type.setItemText(0, _translate("MainWindow", "Acc"))
        self.comboBox_type.setItemText(1, _translate("MainWindow", "Gyro"))
        self.forwardButton_graph.setText(_translate("MainWindow", "Forward"))


